/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TetrisProject;

import java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Gesser
 */
public class Tetris extends javax.swing.JFrame {

    public static JPanel[][] arrJPanel;
    public static JPanel mainMenu;
    public static JPanel playingField;
    public static JPanel gameOver;
    public static String buttonName;

    int mouseX;
    int mouseY;

    /**
     * Creates new form Tetris
     */
    public Tetris() {
        initComponents();

        jPanel2.setVisible(true);    //Главное меню
        jPanel4.setVisible(false);   //Игровое поле
        jPanel206.setVisible(false); //Управление меню
        jPanel208.setVisible(false); //Игра окончина меню
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel208 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        jPanel51 = new javax.swing.JPanel();
        jPanel52 = new javax.swing.JPanel();
        jPanel53 = new javax.swing.JPanel();
        jPanel54 = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        jPanel57 = new javax.swing.JPanel();
        jPanel58 = new javax.swing.JPanel();
        jPanel59 = new javax.swing.JPanel();
        jPanel60 = new javax.swing.JPanel();
        jPanel61 = new javax.swing.JPanel();
        jPanel62 = new javax.swing.JPanel();
        jPanel63 = new javax.swing.JPanel();
        jPanel64 = new javax.swing.JPanel();
        jPanel65 = new javax.swing.JPanel();
        jPanel66 = new javax.swing.JPanel();
        jPanel67 = new javax.swing.JPanel();
        jPanel68 = new javax.swing.JPanel();
        jPanel69 = new javax.swing.JPanel();
        jPanel70 = new javax.swing.JPanel();
        jPanel71 = new javax.swing.JPanel();
        jPanel72 = new javax.swing.JPanel();
        jPanel73 = new javax.swing.JPanel();
        jPanel74 = new javax.swing.JPanel();
        jPanel75 = new javax.swing.JPanel();
        jPanel76 = new javax.swing.JPanel();
        jPanel77 = new javax.swing.JPanel();
        jPanel78 = new javax.swing.JPanel();
        jPanel79 = new javax.swing.JPanel();
        jPanel80 = new javax.swing.JPanel();
        jPanel81 = new javax.swing.JPanel();
        jPanel82 = new javax.swing.JPanel();
        jPanel83 = new javax.swing.JPanel();
        jPanel84 = new javax.swing.JPanel();
        jPanel85 = new javax.swing.JPanel();
        jPanel86 = new javax.swing.JPanel();
        jPanel87 = new javax.swing.JPanel();
        jPanel88 = new javax.swing.JPanel();
        jPanel89 = new javax.swing.JPanel();
        jPanel90 = new javax.swing.JPanel();
        jPanel91 = new javax.swing.JPanel();
        jPanel92 = new javax.swing.JPanel();
        jPanel93 = new javax.swing.JPanel();
        jPanel94 = new javax.swing.JPanel();
        jPanel95 = new javax.swing.JPanel();
        jPanel96 = new javax.swing.JPanel();
        jPanel97 = new javax.swing.JPanel();
        jPanel98 = new javax.swing.JPanel();
        jPanel99 = new javax.swing.JPanel();
        jPanel100 = new javax.swing.JPanel();
        jPanel101 = new javax.swing.JPanel();
        jPanel102 = new javax.swing.JPanel();
        jPanel103 = new javax.swing.JPanel();
        jPanel104 = new javax.swing.JPanel();
        jPanel105 = new javax.swing.JPanel();
        jPanel106 = new javax.swing.JPanel();
        jPanel107 = new javax.swing.JPanel();
        jPanel108 = new javax.swing.JPanel();
        jPanel109 = new javax.swing.JPanel();
        jPanel110 = new javax.swing.JPanel();
        jPanel111 = new javax.swing.JPanel();
        jPanel112 = new javax.swing.JPanel();
        jPanel113 = new javax.swing.JPanel();
        jPanel114 = new javax.swing.JPanel();
        jPanel115 = new javax.swing.JPanel();
        jPanel116 = new javax.swing.JPanel();
        jPanel117 = new javax.swing.JPanel();
        jPanel118 = new javax.swing.JPanel();
        jPanel119 = new javax.swing.JPanel();
        jPanel120 = new javax.swing.JPanel();
        jPanel121 = new javax.swing.JPanel();
        jPanel122 = new javax.swing.JPanel();
        jPanel123 = new javax.swing.JPanel();
        jPanel124 = new javax.swing.JPanel();
        jPanel125 = new javax.swing.JPanel();
        jPanel126 = new javax.swing.JPanel();
        jPanel127 = new javax.swing.JPanel();
        jPanel128 = new javax.swing.JPanel();
        jPanel129 = new javax.swing.JPanel();
        jPanel130 = new javax.swing.JPanel();
        jPanel131 = new javax.swing.JPanel();
        jPanel132 = new javax.swing.JPanel();
        jPanel133 = new javax.swing.JPanel();
        jPanel134 = new javax.swing.JPanel();
        jPanel135 = new javax.swing.JPanel();
        jPanel136 = new javax.swing.JPanel();
        jPanel137 = new javax.swing.JPanel();
        jPanel138 = new javax.swing.JPanel();
        jPanel139 = new javax.swing.JPanel();
        jPanel140 = new javax.swing.JPanel();
        jPanel141 = new javax.swing.JPanel();
        jPanel142 = new javax.swing.JPanel();
        jPanel143 = new javax.swing.JPanel();
        jPanel144 = new javax.swing.JPanel();
        jPanel145 = new javax.swing.JPanel();
        jPanel146 = new javax.swing.JPanel();
        jPanel147 = new javax.swing.JPanel();
        jPanel148 = new javax.swing.JPanel();
        jPanel149 = new javax.swing.JPanel();
        jPanel150 = new javax.swing.JPanel();
        jPanel151 = new javax.swing.JPanel();
        jPanel152 = new javax.swing.JPanel();
        jPanel153 = new javax.swing.JPanel();
        jPanel154 = new javax.swing.JPanel();
        jPanel155 = new javax.swing.JPanel();
        jPanel156 = new javax.swing.JPanel();
        jPanel157 = new javax.swing.JPanel();
        jPanel158 = new javax.swing.JPanel();
        jPanel159 = new javax.swing.JPanel();
        jPanel160 = new javax.swing.JPanel();
        jPanel161 = new javax.swing.JPanel();
        jPanel162 = new javax.swing.JPanel();
        jPanel163 = new javax.swing.JPanel();
        jPanel164 = new javax.swing.JPanel();
        jPanel165 = new javax.swing.JPanel();
        jPanel166 = new javax.swing.JPanel();
        jPanel167 = new javax.swing.JPanel();
        jPanel168 = new javax.swing.JPanel();
        jPanel169 = new javax.swing.JPanel();
        jPanel170 = new javax.swing.JPanel();
        jPanel171 = new javax.swing.JPanel();
        jPanel172 = new javax.swing.JPanel();
        jPanel173 = new javax.swing.JPanel();
        jPanel174 = new javax.swing.JPanel();
        jPanel175 = new javax.swing.JPanel();
        jPanel176 = new javax.swing.JPanel();
        jPanel177 = new javax.swing.JPanel();
        jPanel178 = new javax.swing.JPanel();
        jPanel179 = new javax.swing.JPanel();
        jPanel180 = new javax.swing.JPanel();
        jPanel181 = new javax.swing.JPanel();
        jPanel182 = new javax.swing.JPanel();
        jPanel183 = new javax.swing.JPanel();
        jPanel184 = new javax.swing.JPanel();
        jPanel185 = new javax.swing.JPanel();
        jPanel186 = new javax.swing.JPanel();
        jPanel187 = new javax.swing.JPanel();
        jPanel188 = new javax.swing.JPanel();
        jPanel189 = new javax.swing.JPanel();
        jPanel190 = new javax.swing.JPanel();
        jPanel191 = new javax.swing.JPanel();
        jPanel192 = new javax.swing.JPanel();
        jPanel193 = new javax.swing.JPanel();
        jPanel194 = new javax.swing.JPanel();
        jPanel195 = new javax.swing.JPanel();
        jPanel196 = new javax.swing.JPanel();
        jPanel197 = new javax.swing.JPanel();
        jPanel198 = new javax.swing.JPanel();
        jPanel199 = new javax.swing.JPanel();
        jPanel200 = new javax.swing.JPanel();
        jPanel201 = new javax.swing.JPanel();
        jPanel202 = new javax.swing.JPanel();
        jPanel203 = new javax.swing.JPanel();
        jPanel204 = new javax.swing.JPanel();
        jPanel205 = new javax.swing.JPanel();
        jPanel206 = new javax.swing.JPanel();
        jPanel207 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(235, 235, 235));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TetrisProject/Icons/tetrisv2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 41, 50));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Tetris");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TetrisProject/Icons/closeb.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 352, 40));

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(235, 235, 235));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(39, 41, 50));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("New game");
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 268, 40));

        jLabel5.setBackground(new java.awt.Color(235, 235, 235));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(39, 41, 50));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Control");
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 44, 268, 40));

        jLabel6.setBackground(new java.awt.Color(235, 235, 235));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(39, 41, 50));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Quit");
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 86, 268, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 247, 272, 128));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 352, 622));

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel208.setBackground(new java.awt.Color(245, 245, 245));
        jPanel208.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(235, 235, 235));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(39, 41, 50));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Game");
        jLabel17.setOpaque(true);
        jPanel208.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 27, 106, 25));

        jLabel18.setBackground(new java.awt.Color(235, 235, 235));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(39, 41, 50));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("over");
        jLabel18.setOpaque(true);
        jPanel208.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 54, 106, 25));

        jPanel4.add(jPanel208, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 258, 214, 106));

        jPanel7.setBackground(new java.awt.Color(245, 245, 245));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 25, 25));

        jPanel6.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 2, 25, 25));

        jPanel8.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 2, 25, 25));

        jPanel9.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 2, 25, 25));

        jPanel10.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 2, 25, 25));

        jPanel11.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 2, 25, 25));

        jPanel12.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 2, 25, 25));

        jPanel13.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 2, 25, 25));

        jPanel14.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 2, 25, 25));

        jPanel15.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 2, 25, 25));

        jPanel16.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 29, 25, 25));

        jPanel17.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 29, 25, 25));

        jPanel18.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 29, 25, 25));

        jPanel19.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 29, 25, 25));

        jPanel20.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 29, 25, 25));

        jPanel21.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 29, 25, 25));

        jPanel22.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 29, 25, 25));

        jPanel23.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 29, 25, 25));

        jPanel24.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 29, 25, 25));

        jPanel25.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 29, 25, 25));

        jPanel26.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 56, 25, 25));

        jPanel27.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 56, 25, 25));

        jPanel28.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 56, 25, 25));

        jPanel29.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 56, 25, 25));

        jPanel30.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 56, 25, 25));

        jPanel31.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 56, 25, 25));

        jPanel32.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 56, 25, 25));

        jPanel33.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 56, 25, 25));

        jPanel34.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 56, 25, 25));

        jPanel35.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 56, 25, 25));

        jPanel36.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 83, 25, 25));

        jPanel37.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 83, 25, 25));

        jPanel38.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 83, 25, 25));

        jPanel39.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 83, 25, 25));

        jPanel40.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 83, 25, 25));

        jPanel41.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 83, 25, 25));

        jPanel42.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 83, 25, 25));

        jPanel43.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 83, 25, 25));

        jPanel44.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 83, 25, 25));

        jPanel45.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 83, 25, 25));

        jPanel46.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 110, 25, 25));

        jPanel47.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 110, 25, 25));

        jPanel48.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 110, 25, 25));

        jPanel49.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 110, 25, 25));

        jPanel50.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 25, 25));

        jPanel51.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 110, 25, 25));

        jPanel52.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 110, 25, 25));

        jPanel53.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 110, 25, 25));

        jPanel54.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 110, 25, 25));

        jPanel55.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 110, 25, 25));

        jPanel56.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 137, 25, 25));

        jPanel57.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 137, 25, 25));

        jPanel58.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 137, 25, 25));

        jPanel59.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 137, 25, 25));

        jPanel60.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 137, 25, 25));

        jPanel61.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 137, 25, 25));

        jPanel62.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 137, 25, 25));

        jPanel63.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 137, 25, 25));

        jPanel64.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 137, 25, 25));

        jPanel65.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 137, 25, 25));

        jPanel66.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 164, 25, 25));

        jPanel67.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 164, 25, 25));

        jPanel68.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 164, 25, 25));

        jPanel69.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 164, 25, 25));

        jPanel70.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 164, 25, 25));

        jPanel71.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 164, 25, 25));

        jPanel72.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 164, 25, 25));

        jPanel73.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 164, 25, 25));

        jPanel74.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 164, 25, 25));

        jPanel75.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 164, 25, 25));

        jPanel76.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 191, 25, 25));

        jPanel77.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 191, 25, 25));

        jPanel78.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 191, 25, 25));

        jPanel79.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 191, 25, 25));

        jPanel80.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 191, 25, 25));

        jPanel81.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 191, 25, 25));

        jPanel82.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 191, 25, 25));

        jPanel83.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 191, 25, 25));

        jPanel84.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 191, 25, 25));

        jPanel85.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 191, 25, 25));

        jPanel86.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 218, 25, 25));

        jPanel87.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 218, 25, 25));

        jPanel88.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 218, 25, 25));

        jPanel89.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 218, 25, 25));

        jPanel90.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 218, 25, 25));

        jPanel91.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 218, 25, 25));

        jPanel92.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 218, 25, 25));

        jPanel93.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 218, 25, 25));

        jPanel94.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 218, 25, 25));

        jPanel95.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 218, 25, 25));

        jPanel96.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 245, 25, 25));

        jPanel97.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 245, 25, 25));

        jPanel98.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 245, 25, 25));

        jPanel99.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 245, 25, 25));

        jPanel100.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 245, 25, 25));

        jPanel101.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 245, 25, 25));

        jPanel102.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 245, 25, 25));

        jPanel103.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 245, 25, 25));

        jPanel104.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 245, 25, 25));

        jPanel105.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 245, 25, 25));

        jPanel106.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 272, 25, 25));

        jPanel107.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 272, 25, 25));

        jPanel108.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 272, 25, 25));

        jPanel109.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 272, 25, 25));

        jPanel110.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 272, 25, 25));

        jPanel111.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 272, 25, 25));

        jPanel112.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 272, 25, 25));

        jPanel113.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 272, 25, 25));

        jPanel114.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 272, 25, 25));

        jPanel115.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 272, 25, 25));

        jPanel116.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 299, 25, 25));

        jPanel117.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 299, 25, 25));

        jPanel118.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 299, 25, 25));

        jPanel119.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 299, 25, 25));

        jPanel120.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 299, 25, 25));

        jPanel121.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 299, 25, 25));

        jPanel122.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 299, 25, 25));

        jPanel123.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 299, 25, 25));

        jPanel124.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 299, 25, 25));

        jPanel125.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 299, 25, 25));

        jPanel126.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 326, 25, 25));

        jPanel127.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 326, 25, 25));

        jPanel128.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 326, 25, 25));

        jPanel129.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 326, 25, 25));

        jPanel130.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 326, 25, 25));

        jPanel131.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 326, 25, 25));

        jPanel132.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 326, 25, 25));

        jPanel133.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 326, 25, 25));

        jPanel134.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 326, 25, 25));

        jPanel135.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 326, 25, 25));

        jPanel136.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 353, 25, 25));

        jPanel137.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 353, 25, 25));

        jPanel138.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 353, 25, 25));

        jPanel139.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel139, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 353, 25, 25));

        jPanel140.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel140, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 353, 25, 25));

        jPanel141.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 353, 25, 25));

        jPanel142.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel142, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 353, 25, 25));

        jPanel143.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel143, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 353, 25, 25));

        jPanel144.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel144, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 353, 25, 25));

        jPanel145.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel145, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 353, 25, 25));

        jPanel146.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel146, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 380, 25, 25));

        jPanel147.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel147, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 380, 25, 25));

        jPanel148.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel148, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 380, 25, 25));

        jPanel149.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel149, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 380, 25, 25));

        jPanel150.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel150, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 25, 25));

        jPanel151.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel151, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 380, 25, 25));

        jPanel152.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel152, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 380, 25, 25));

        jPanel153.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel153, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 380, 25, 25));

        jPanel154.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel154, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 380, 25, 25));

        jPanel155.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel155, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 380, 25, 25));

        jPanel156.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel156, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 407, 25, 25));

        jPanel157.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel157, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 407, 25, 25));

        jPanel158.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel158, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 407, 25, 25));

        jPanel159.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel159, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 407, 25, 25));

        jPanel160.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel160, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 407, 25, 25));

        jPanel161.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel161, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 407, 25, 25));

        jPanel162.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel162, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 407, 25, 25));

        jPanel163.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel163, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 407, 25, 25));

        jPanel164.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel164, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 407, 25, 25));

        jPanel165.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel165, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 407, 25, 25));

        jPanel166.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel166, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 434, 25, 25));

        jPanel167.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel167, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 434, 25, 25));

        jPanel168.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel168, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 434, 25, 25));

        jPanel169.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel169, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 434, 25, 25));

        jPanel170.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel170, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 434, 25, 25));

        jPanel171.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel171, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 434, 25, 25));

        jPanel172.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel172, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 434, 25, 25));

        jPanel173.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel173, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 434, 25, 25));

        jPanel174.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel174, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 434, 25, 25));

        jPanel175.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel175, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 434, 25, 25));

        jPanel176.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel176, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 461, 25, 25));

        jPanel177.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel177, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 461, 25, 25));

        jPanel178.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel178, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 461, 25, 25));

        jPanel179.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel179, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 461, 25, 25));

        jPanel180.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel180, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 461, 25, 25));

        jPanel181.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel181, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 461, 25, 25));

        jPanel182.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel182, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 461, 25, 25));

        jPanel183.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel183, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 461, 25, 25));

        jPanel184.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel184, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 461, 25, 25));

        jPanel185.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel185, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 461, 25, 25));

        jPanel186.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel186, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 488, 25, 25));

        jPanel187.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel187, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 488, 25, 25));

        jPanel188.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel188, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 488, 25, 25));

        jPanel189.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel189, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 488, 25, 25));

        jPanel190.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel190, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 488, 25, 25));

        jPanel191.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel191, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 488, 25, 25));

        jPanel192.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel192, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 488, 25, 25));

        jPanel193.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel193, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 488, 25, 25));

        jPanel194.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel194, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 488, 25, 25));

        jPanel195.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel195, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 488, 25, 25));

        jPanel196.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel196, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 515, 25, 25));

        jPanel197.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel197, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 515, 25, 25));

        jPanel198.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel198, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 515, 25, 25));

        jPanel199.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel199, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 515, 25, 25));

        jPanel200.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel200, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 515, 25, 25));

        jPanel201.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel201, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 515, 25, 25));

        jPanel202.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel202, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 515, 25, 25));

        jPanel203.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel203, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 515, 25, 25));

        jPanel204.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel204, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 515, 25, 25));

        jPanel205.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.add(jPanel205, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 515, 25, 25));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 272, 542));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 352, 622));

        jPanel206.setBackground(new java.awt.Color(245, 245, 245));
        jPanel206.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel207.setBackground(new java.awt.Color(245, 245, 245));
        jPanel207.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(235, 235, 235));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(39, 41, 50));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Space");
        jLabel7.setOpaque(true);
        jPanel207.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 133, 40));

        jLabel11.setBackground(new java.awt.Color(235, 235, 235));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(39, 41, 50));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Rotation");
        jLabel11.setOpaque(true);
        jPanel207.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 2, 133, 40));

        jLabel8.setBackground(new java.awt.Color(235, 235, 235));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(39, 41, 50));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("←");
        jLabel8.setOpaque(true);
        jPanel207.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 44, 133, 40));

        jLabel12.setBackground(new java.awt.Color(235, 235, 235));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(39, 41, 50));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Step left");
        jLabel12.setOpaque(true);
        jPanel207.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 44, 133, 40));

        jLabel9.setBackground(new java.awt.Color(235, 235, 235));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(39, 41, 50));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("↓");
        jLabel9.setOpaque(true);
        jPanel207.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 86, 133, 40));

        jLabel13.setBackground(new java.awt.Color(235, 235, 235));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(39, 41, 50));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Skip step");
        jLabel13.setOpaque(true);
        jPanel207.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 86, 133, 40));

        jLabel10.setBackground(new java.awt.Color(235, 235, 235));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(39, 41, 50));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("→");
        jLabel10.setOpaque(true);
        jPanel207.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 128, 133, 40));

        jLabel14.setBackground(new java.awt.Color(235, 235, 235));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(39, 41, 50));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Step right");
        jLabel14.setOpaque(true);
        jPanel207.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 128, 133, 40));

        jLabel15.setBackground(new java.awt.Color(235, 235, 235));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(39, 41, 50));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Main menu");
        jLabel15.setOpaque(true);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
        });
        jPanel207.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 170, 268, 40));

        jPanel206.add(jPanel207, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 205, 272, 212));

        getContentPane().add(jPanel206, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 352, 622));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /* Закрыть окно */
    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        //jLabel3.setIcon(new ImageIcon(getClass().getResource("/TetrisProject/Icons/closeb.png")));
        jLabel3.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        //jLabel3.setIcon(new ImageIcon(getClass().getResource("/TetrisProject/Icons/closeg.png")));
        jLabel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel3MouseExited

    /* Новая игра */
    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        jPanel2.setVisible(false);  //Главное меню
        jPanel4.setVisible(true);   //Игровое поле

        /* Массив игрового поля */
        arrJPanel = new JPanel[][]{
            {jPanel5, jPanel6, jPanel8, jPanel9, jPanel10, jPanel11, jPanel12, jPanel13, jPanel14, jPanel15},
            {jPanel16, jPanel17, jPanel18, jPanel19, jPanel20, jPanel21, jPanel22, jPanel23, jPanel24, jPanel25},
            {jPanel26, jPanel27, jPanel28, jPanel29, jPanel30, jPanel31, jPanel32, jPanel33, jPanel34, jPanel35},
            {jPanel36, jPanel37, jPanel38, jPanel39, jPanel40, jPanel41, jPanel42, jPanel43, jPanel44, jPanel45},
            {jPanel46, jPanel47, jPanel48, jPanel49, jPanel50, jPanel51, jPanel52, jPanel53, jPanel54, jPanel55},
            {jPanel56, jPanel57, jPanel58, jPanel59, jPanel60, jPanel61, jPanel62, jPanel63, jPanel64, jPanel65},
            {jPanel66, jPanel67, jPanel68, jPanel69, jPanel70, jPanel71, jPanel72, jPanel73, jPanel74, jPanel75},
            {jPanel76, jPanel77, jPanel78, jPanel79, jPanel80, jPanel81, jPanel82, jPanel83, jPanel84, jPanel85},
            {jPanel86, jPanel87, jPanel88, jPanel89, jPanel90, jPanel91, jPanel92, jPanel93, jPanel94, jPanel95},
            {jPanel96, jPanel97, jPanel98, jPanel99, jPanel100, jPanel101, jPanel102, jPanel103, jPanel104, jPanel105},
            {jPanel106, jPanel107, jPanel108, jPanel109, jPanel110, jPanel111, jPanel112, jPanel113, jPanel114, jPanel115},
            {jPanel116, jPanel117, jPanel118, jPanel119, jPanel120, jPanel121, jPanel122, jPanel123, jPanel124, jPanel125},
            {jPanel126, jPanel127, jPanel128, jPanel129, jPanel130, jPanel131, jPanel132, jPanel133, jPanel134, jPanel135},
            {jPanel136, jPanel137, jPanel138, jPanel139, jPanel140, jPanel141, jPanel142, jPanel143, jPanel144, jPanel145},
            {jPanel146, jPanel147, jPanel148, jPanel149, jPanel150, jPanel151, jPanel152, jPanel153, jPanel154, jPanel155},
            {jPanel156, jPanel157, jPanel158, jPanel159, jPanel160, jPanel161, jPanel162, jPanel163, jPanel164, jPanel165},
            {jPanel166, jPanel167, jPanel168, jPanel169, jPanel170, jPanel171, jPanel172, jPanel173, jPanel174, jPanel175},
            {jPanel176, jPanel177, jPanel178, jPanel179, jPanel180, jPanel181, jPanel182, jPanel183, jPanel184, jPanel185},
            {jPanel186, jPanel187, jPanel188, jPanel189, jPanel190, jPanel191, jPanel192, jPanel193, jPanel194, jPanel195},
            {jPanel196, jPanel197, jPanel198, jPanel199, jPanel200, jPanel201, jPanel202, jPanel203, jPanel204, jPanel205}
        };

        mainMenu = jPanel2;
        playingField = jPanel4;
        gameOver = jPanel208;

        buttonName = new String();

        ThreadNewGame tng = new ThreadNewGame();
        tng.start();
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel4MouseExited

    /* Управление */
    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        jPanel2.setVisible(false);
        jPanel206.setVisible(true);
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel5MouseExited

    /* Выход */
    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel6MouseExited

    /* Обработчик клавиатуры */
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        switch (evt.getKeyCode()) {
            case KeyEvent.VK_LEFT: {
                buttonName = "Left";
            }
            break;

            case KeyEvent.VK_RIGHT: {
                buttonName = "Right";
            }
            break;

            case KeyEvent.VK_DOWN: {
                buttonName = "Down";
            }
            break;

            case KeyEvent.VK_SPACE: {
                buttonName = "Space";
            }
            break;
        }
    }//GEN-LAST:event_formKeyPressed

    /* Управление (кнопка главного меню) */
    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        jPanel2.setVisible(true);
        jPanel206.setVisible(false);
    }//GEN-LAST:event_jLabel15MousePressed

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        jLabel15.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        jLabel15.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel15MouseExited

    /* Перемещение окна */
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int screenX = evt.getXOnScreen();
        int screenY = evt.getYOnScreen();

        this.setLocation(screenX - mouseX, screenY - mouseY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tetris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel100;
    private javax.swing.JPanel jPanel101;
    private javax.swing.JPanel jPanel102;
    private javax.swing.JPanel jPanel103;
    private javax.swing.JPanel jPanel104;
    private javax.swing.JPanel jPanel105;
    private javax.swing.JPanel jPanel106;
    private javax.swing.JPanel jPanel107;
    private javax.swing.JPanel jPanel108;
    private javax.swing.JPanel jPanel109;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel110;
    private javax.swing.JPanel jPanel111;
    private javax.swing.JPanel jPanel112;
    private javax.swing.JPanel jPanel113;
    private javax.swing.JPanel jPanel114;
    private javax.swing.JPanel jPanel115;
    private javax.swing.JPanel jPanel116;
    private javax.swing.JPanel jPanel117;
    private javax.swing.JPanel jPanel118;
    private javax.swing.JPanel jPanel119;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel120;
    private javax.swing.JPanel jPanel121;
    private javax.swing.JPanel jPanel122;
    private javax.swing.JPanel jPanel123;
    private javax.swing.JPanel jPanel124;
    private javax.swing.JPanel jPanel125;
    private javax.swing.JPanel jPanel126;
    private javax.swing.JPanel jPanel127;
    private javax.swing.JPanel jPanel128;
    private javax.swing.JPanel jPanel129;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel130;
    private javax.swing.JPanel jPanel131;
    private javax.swing.JPanel jPanel132;
    private javax.swing.JPanel jPanel133;
    private javax.swing.JPanel jPanel134;
    private javax.swing.JPanel jPanel135;
    private javax.swing.JPanel jPanel136;
    private javax.swing.JPanel jPanel137;
    private javax.swing.JPanel jPanel138;
    private javax.swing.JPanel jPanel139;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel140;
    private javax.swing.JPanel jPanel141;
    private javax.swing.JPanel jPanel142;
    private javax.swing.JPanel jPanel143;
    private javax.swing.JPanel jPanel144;
    private javax.swing.JPanel jPanel145;
    private javax.swing.JPanel jPanel146;
    private javax.swing.JPanel jPanel147;
    private javax.swing.JPanel jPanel148;
    private javax.swing.JPanel jPanel149;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel150;
    private javax.swing.JPanel jPanel151;
    private javax.swing.JPanel jPanel152;
    private javax.swing.JPanel jPanel153;
    private javax.swing.JPanel jPanel154;
    private javax.swing.JPanel jPanel155;
    private javax.swing.JPanel jPanel156;
    private javax.swing.JPanel jPanel157;
    private javax.swing.JPanel jPanel158;
    private javax.swing.JPanel jPanel159;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel160;
    private javax.swing.JPanel jPanel161;
    private javax.swing.JPanel jPanel162;
    private javax.swing.JPanel jPanel163;
    private javax.swing.JPanel jPanel164;
    private javax.swing.JPanel jPanel165;
    private javax.swing.JPanel jPanel166;
    private javax.swing.JPanel jPanel167;
    private javax.swing.JPanel jPanel168;
    private javax.swing.JPanel jPanel169;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel170;
    private javax.swing.JPanel jPanel171;
    private javax.swing.JPanel jPanel172;
    private javax.swing.JPanel jPanel173;
    private javax.swing.JPanel jPanel174;
    private javax.swing.JPanel jPanel175;
    private javax.swing.JPanel jPanel176;
    private javax.swing.JPanel jPanel177;
    private javax.swing.JPanel jPanel178;
    private javax.swing.JPanel jPanel179;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel180;
    private javax.swing.JPanel jPanel181;
    private javax.swing.JPanel jPanel182;
    private javax.swing.JPanel jPanel183;
    private javax.swing.JPanel jPanel184;
    private javax.swing.JPanel jPanel185;
    private javax.swing.JPanel jPanel186;
    private javax.swing.JPanel jPanel187;
    private javax.swing.JPanel jPanel188;
    private javax.swing.JPanel jPanel189;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel190;
    private javax.swing.JPanel jPanel191;
    private javax.swing.JPanel jPanel192;
    private javax.swing.JPanel jPanel193;
    private javax.swing.JPanel jPanel194;
    private javax.swing.JPanel jPanel195;
    private javax.swing.JPanel jPanel196;
    private javax.swing.JPanel jPanel197;
    private javax.swing.JPanel jPanel198;
    private javax.swing.JPanel jPanel199;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel200;
    private javax.swing.JPanel jPanel201;
    private javax.swing.JPanel jPanel202;
    private javax.swing.JPanel jPanel203;
    private javax.swing.JPanel jPanel204;
    private javax.swing.JPanel jPanel205;
    private javax.swing.JPanel jPanel206;
    private javax.swing.JPanel jPanel207;
    private javax.swing.JPanel jPanel208;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JPanel jPanel77;
    private javax.swing.JPanel jPanel78;
    private javax.swing.JPanel jPanel79;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel80;
    private javax.swing.JPanel jPanel81;
    private javax.swing.JPanel jPanel82;
    private javax.swing.JPanel jPanel83;
    private javax.swing.JPanel jPanel84;
    private javax.swing.JPanel jPanel85;
    private javax.swing.JPanel jPanel86;
    private javax.swing.JPanel jPanel87;
    private javax.swing.JPanel jPanel88;
    private javax.swing.JPanel jPanel89;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel90;
    private javax.swing.JPanel jPanel91;
    private javax.swing.JPanel jPanel92;
    private javax.swing.JPanel jPanel93;
    private javax.swing.JPanel jPanel94;
    private javax.swing.JPanel jPanel95;
    private javax.swing.JPanel jPanel96;
    private javax.swing.JPanel jPanel97;
    private javax.swing.JPanel jPanel98;
    private javax.swing.JPanel jPanel99;
    // End of variables declaration//GEN-END:variables
}
